# Generated by Django 3.2.3 on 2021-05-28 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Myyjat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nimi', models.CharField(default='tyhja', max_length=50)),
                ('puhelinnumero', models.CharField(default='00000000', max_length=20)),
                ('email', models.EmailField(default='etu.suku@malli.fi', max_length=50)),
            ],
            options={
                'ordering': ['nimi'],
            },
        ),
        migrations.CreateModel(
            name='Autot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merkki', models.CharField(default='merkki', max_length=20)),
                ('malli', models.CharField(default='malli', max_length=20)),
                ('vuosimalli', models.IntegerField(default=2021)),
                ('mittarilukema', models.IntegerField(default=0)),
                ('vari', models.CharField(default='auton väri', max_length=20)),
                ('hinta', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('myyja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.myyjat')),
            ],
            options={
                'ordering': ['hinta'],
            },
        ),
    ]
