# Generated by Django 3.2.3 on 2021-05-28 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Autot',
            new_name='Auto',
        ),
        migrations.RenameModel(
            old_name='Myyjat',
            new_name='Myyja',
        ),
    ]
