# Generated by Django 3.2.3 on 2021-05-28 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210528_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='myyja',
            name='titteli',
            field=models.CharField(default='titteli', max_length=50),
        ),
    ]
